const CONFIG = {
  API_BASE_URL: "http://localhost:8000",

  API_ENDPOINTS: {
    HEALTH: "/api/health",
    SITE_CONFIG: "/api/site-config",
    PROPERTIES: "/api/properties/",
    PROPERTY: (slug) => `/api/properties/${slug}`,
    SERVICES: "/api/services/",
    SERVICE: (slug) => `/api/services/${slug}`,
    BOOKINGS: "/api/bookings/",
    BOOKING: (ref) => `/api/bookings/${ref}`,
  },

  SITE_NAME: "PuriGuide",
  SITE_TAGLINE: "Your Complete Puri Travel Companion",
  SITE_PHONE: "+91-XXXXXXXXXX",
  SITE_WHATSAPP: "+91-XXXXXXXXXX",
  SITE_EMAIL: "contact@puriguide.in",
  FACEBOOK_URL: "https://facebook.com/puriguide",
  INSTAGRAM_URL: "https://instagram.com/puriguide",

  HERO_TITLE: "Discover Sacred & Serene Puri",
  HERO_SUBTITLE:
    "Your complete travel companion for temples, homestays, local food, and experiences in the holiest beach city of India.",
  HERO_CTA_PRIMARY: "Explore the Guide",
  HERO_CTA_SECONDARY: "Book a Homestay",

  IMAGES: {
    HERO_BG: "images/asiyana/hall.jpg",
    ASIYANA_MAIN: "images/asiyana/hall.jpg",
    ASIYANA_BEDROOM: "images/asiyana/bedroom.jpg",
    ASIYANA_KITCHEN: "images/asiyana/kitchen.jpg",
    ASIYANA_SEAVIEW: "images/asiyana/rooftop_seaview.jpg",
    TULSI_MAIN: "images/tulsi-vihar/bedroom.jpg",
    TULSI_BEDROOM: "images/tulsi-vihar/bedroom.jpg",
    TULSI_KITCHEN: "images/tulsi-vihar/kitchen.jpg",
    TULSI_BALCONY: "images/tulsi-vihar/balcony.jpg",
    JAGANNATH_TEMPLE: "images/placeholders/jagannath-temple.jpg",
    KONARK_TEMPLE: "images/placeholders/konark-temple.jpg",
    BEDI_HANUMAN: "images/placeholders/bedi-hanuman.jpg",
    MAHAVIR_TEMPLE: "images/placeholders/mahavir-temple.jpg",
    CHILIKA_LAKE: "images/placeholders/chilika-lake.jpg",
    CAR_RENTAL: "images/placeholders/car-rental.jpg",
    BIKE_RENTAL: "images/placeholders/bike-rental.jpg",
    AIRPORT_TRANSFER: "images/placeholders/airport-transfer.jpg",
    CRICKET_COACHING: "images/placeholders/cricket-coaching.jpg",
    FOOD_MACHHA: "images/placeholders/machha-jhola.jpg",
    FOOD_DALMA: "images/placeholders/dalma.jpg",
    FOOD_CHHENA: "images/placeholders/chhena-poda.jpg",
    FOOD_SEAFOOD: "images/placeholders/seafood.jpg",
  },

  PLACEHOLDER: {
    BG_COLOR: "#F5EDD8",
    TEXT_COLOR: "#6B4C3B",
    SHOW_LABEL: true,
  },

  TEMPLES: [
    {
      id: "jagannath",
      name: "Jagannath Temple",
      slug: "jagannath-temple",
      emoji: "🛕",
      tag: "Must Visit",
      tagColor: "#E8610A",
      description:
        "One of the four sacred dhams of India. The magnificent temple dedicated to Lord Jagannath stands tall at the heart of Puri.",
      darshan_timings: "5:00 AM - 9:00 PM",
      entry_fee: "Free (for Hindus)",
      dress_code: "Traditional Indian attire required",
      tips: "Arrive early for morning darshan. Non-Hindus cannot enter inside.",
      distance_from_beach: "1.5 km",
      image_key: "JAGANNATH_TEMPLE",
    },
    {
      id: "konark",
      name: "Konark Sun Temple",
      slug: "konark-sun-temple",
      emoji: "☀️",
      tag: "UNESCO",
      tagColor: "#0E6B8A",
      description:
        "A 13th century masterpiece of Odishan architecture dedicated to the Sun God. A UNESCO World Heritage Site.",
      darshan_timings: "6:00 AM - 8:00 PM",
      entry_fee: "₹40 (Indian) / ₹600 (Foreign)",
      light_sound_show: "7:00 PM daily",
      distance_from_puri: "35 km",
      tips: "Visit early morning or late afternoon for best light and fewer crowds.",
      image_key: "KONARK_TEMPLE",
    },
    {
      id: "bedi-hanuman",
      name: "Bedi Hanuman Temple",
      slug: "bedi-hanuman-temple",
      emoji: "🙏",
      tag: "Unique",
      tagColor: "#C9973A",
      description:
        "A unique temple where Lord Hanuman is depicted in chains (bedi). Located on the seashore, it has a fascinating legend.",
      timings: "5:00 AM - 9:00 PM",
      entry_fee: "Free",
      location: "Puri sea beach road",
      image_key: "BEDI_HANUMAN",
    },
    {
      id: "mahavir",
      name: "Mahavir Temple",
      slug: "mahavir-temple",
      emoji: "🔱",
      tag: "Sacred",
      tagColor: "#3D2B1F",
      description:
        "A revered Hanuman temple in the heart of Puri city, visited by thousands of devotees daily.",
      timings: "6:00 AM - 9:00 PM",
      entry_fee: "Free",
      image_key: "MAHAVIR_TEMPLE",
    },
    {
      id: "chilika",
      name: "Chilika Lake",
      slug: "chilika-lake",
      emoji: "🐦",
      tag: "Day Trip",
      tagColor: "#1A8FAD",
      description:
        "Asia's largest brackish water lagoon. Famous for Irrawaddy dolphins, migratory birds, and the Kalijai Temple island.",
      distance_from_puri: "50 km",
      best_time: "November to February",
      activities: "Boat rides, bird watching, dolphin spotting",
      image_key: "CHILIKA_LAKE",
    },
  ],

  SERVICES: [
    {
      id: "car-rental",
      name: "Car Rental",
      slug: "car-rental",
      icon: "fa-car",
      emoji: "🚗",
      description:
        "AC cars with experienced local drivers. Day trips to Konark, Chilika Lake, Bhubaneswar and more.",
      price: 1500,
      price_unit: "per day",
      contact: "Caretaker",
      image_key: "CAR_RENTAL",
    },
    {
      id: "bike-rental",
      name: "Bike Rental",
      slug: "bike-rental",
      icon: "fa-motorcycle",
      emoji: "🛵",
      description:
        "Explore Puri at your own pace. Scooters and motorcycles available by the hour or day.",
      price: 300,
      price_unit: "per day",
      contact: "Caretaker",
      image_key: "BIKE_RENTAL",
    },
    {
      id: "airport-transfer",
      name: "Airport Transfer",
      slug: "airport-transfer",
      icon: "fa-plane",
      emoji: "✈️",
      description:
        "Pickup and drop from Bhubaneswar Airport (BBI). Comfortable AC vehicle. On time, every time.",
      price: 1800,
      price_unit: "per trip",
      contact: "Caretaker",
      image_key: "AIRPORT_TRANSFER",
    },
    {
      id: "station-transfer",
      name: "Railway Station Transfer",
      slug: "station-transfer",
      icon: "fa-train",
      emoji: "🚂",
      description:
        "Pickup and drop from Puri Railway Station. Available 24/7.",
      price: 300,
      price_unit: "per trip",
      contact: "Caretaker",
      image_key: "AIRPORT_TRANSFER",
    },
    {
      id: "cricket-coaching",
      name: "Cricket Coaching",
      slug: "cricket-coaching",
      icon: "fa-baseball-bat-ball",
      emoji: "🏏",
      description:
        "Book a throw-down session with a professional coach at Sobers Sporting Academy. Nets available daily.",
      price: 500,
      price_unit: "per session",
      contact: "Sobers Sporting",
      image_key: "CRICKET_COACHING",
    },
    {
      id: "temple-tour",
      name: "Guided Temple Tour",
      slug: "temple-tour",
      icon: "fa-map-location-dot",
      emoji: "🗺️",
      description:
        "Curated half-day and full-day tours to temples, markets, and heritage sites with knowledgeable local guides.",
      price: 800,
      price_unit: "per day",
      contact: "Caretaker",
      image_key: "JAGANNATH_TEMPLE",
    },
  ],

  FOOD: [
    {
      name: "Machha Jhola",
      emoji: "🐟",
      description:
        "Traditional Odia fish curry with mustard and turmeric. A staple at every local home and restaurant.",
      where_to_eat: "Peace Restaurant, Wild Grass Restaurant",
      image_key: "FOOD_MACHHA",
    },
    {
      name: "Dalma",
      emoji: "🥘",
      description:
        "Lentils cooked with vegetables — the soul food of Odisha. Offered as Mahaprasad at Jagannath Temple.",
      where_to_eat: "Any local Odia thali restaurant",
      image_key: "FOOD_DALMA",
    },
    {
      name: "Chhena Poda",
      emoji: "🍮",
      description:
        "Lord Jagannath's favourite sweet — caramelized cottage cheese baked to perfection. A must-try.",
      where_to_eat: "Pahala shops, local sweet shops near temple",
      image_key: "FOOD_CHHENA",
    },
    {
      name: "Beach Seafood",
      emoji: "🦐",
      description:
        "Freshly grilled prawns, crabs and fish right on the Puri beach. Best enjoyed at sunset.",
      where_to_eat: "Beach shacks along Puri sea beach",
      image_key: "FOOD_SEAFOOD",
    },
  ],

  BOOKING: {
    SERVICE_TYPES: [
      { value: "homestay", label: "Homestay Booking" },
      { value: "car", label: "Car Rental" },
      { value: "bike", label: "Bike Rental" },
      { value: "airport_transfer", label: "Airport Transfer" },
      { value: "station_transfer", label: "Station Transfer" },
      { value: "cricket", label: "Cricket Coaching" },
      { value: "temple_tour", label: "Guided Temple Tour" },
    ],
    MIN_STAY_NIGHTS: 1,
    ADVANCE_BOOKING_DAYS: 1,
    CONFIRMATION_MESSAGE:
      "Booking received! Our caretaker will contact you on WhatsApp within 2 hours.",
    WHATSAPP_MESSAGE_TEMPLATE:
      "Hi, I would like to book {service} from {checkin} to {checkout} for {guests} guests. My name is {name}.",
  },
};
